config/routes.rb
Fplplayerhistory::Application.routes.draw do
  get "scrapers/launch"
  match 'scrapers/launch' => 'scrapers#start', :via => :post, as: 'scraper_start'
  
  get "top_10_bar" => 'graphs#top_10_bar', as: :top_10_bar
  post "graphs/chosen_players", to: 'graphs#chosen_players', as: :chosen_players

  get "player/comparison", to: 'player#comparison', as: :comparison
  post "player/filter", to: 'player#filter', as: :filter

  root 'player#comparison'

  

end

app/models/club.rb
class Club < ActiveRecord::Base
	has_many :players
end

app/models/player.rb
class Player < ActiveRecord::Base
	belongs_to :club
	has_many :player_histories

	scope :venue_split, ->(player_id) do 
		where("players.id in (?)", player_id)
		.joins("INNER JOIN player_histories ON player_histories.player_id = players.id
			INNER JOIN clubs ON clubs.id = players.club_id")
		.select("players.id, players.name as web_name, clubs.name as club, players.total_points, 
			venue, count(1) as games, sum(points) as points")
		.group("players.id,player_histories.venue, clubs.name") 
	end
	scope :stats, ->(fstround = 1, lstround= 38) do
		where("ph.round >= (?) and ph.round <= (?)",fstround,lstround)
		.joins("as p INNER JOIN player_histories as ph ON ph.player_id = p.id
			INNER JOIN clubs on clubs.id = p.club_id")
		.select("p.id as id,p.name as name, p.position, 
			round(p.cost_now,1)/10 as cost_now,
			sum(ph.points) as points, 
			round(sum(round(ph.points*10, 2)/round(ph.value,2)),2) as range_value,
			sum(ph.miniutes_played) as miniutes_played, 
			sum(ph.goals_scored) as goals_scored, 
			sum(ph.assists) as assists, 
			sum(ph.clean_sheets) as clean_sheets, 
			sum(ph.goals_conceded) as goals_conceded, 
			sum(ph.own_goals) as own_goals, 
			sum(ph.penalty_saves) as penalty_saves, 
			sum(ph.penalty_missed) as penalty_missed, 
			sum(ph.yellow_cards) as yellow_cards, 
			sum(ph.red_cards) as red_cards, 
			sum(ph.saves) as saves, 
			sum(ph.bonus) as bonus, 
			sum(ph.esp) as esp, 
			sum(ph.net_transfers) as net_transfers,
			round(sum(round(ph.miniutes_played,2)/80)) as games,
			round(sum(case  
				when ph.miniutes_played > 0 then round(ph.points,3)/ph.miniutes_played
				else 0
				end),2) as points_per_min,
			round(case when sum(ph.points) > 0 then
				round(sum(ph.points),2)/
						sum(case
							when ph.miniutes_played > 0 then 1
							else 0
			 			end)
					else 0 end,2) as points_per_game,
			clubs.name as clubname")
		.group("p.id, p.position, p.cost_now, clubs.name")
	end
	scope :by_name, ->(name) do
		where("players.name = (?)", name)
	end
end

app/models/player_history.rb
class PlayerHistory < ActiveRecord::Base
	has_one :player
	scope :by_venue, ->(location) do
		where("venue = (?)", location)
	end
end

app/models/scraper.rb
class Scraper < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
	def top_10_bar
		aj = if params[:aj]
			params[:aj]
		else
			false
		end
	#	@data = Player.order(total_points: :desc).limit(10) unless aj
#		x= Player.venue_split([214, 100])
		# logger.debug  x[0].web_name
		# logger.debug  x[1].web_name
		# logger.debug  x.size
		@players = Player.paginate(:per_page => 10, :page => params[:page] || 1)
		respond_to do |format|
			format.html
			format.js { render layout: false }
		end
	end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
	def comparison
		@players = Player.stats
	end
	def filter
		@players = Player.stats(params[:rounds_from].to_i, params[:rounds_to].to_i)
		@players = @players.where("p.cost_now >= (?) and p.cost_now <= (?)", 
			(params[:price_from].to_f*10), (params[:price_to].to_f*10))
		condition("ph.venue = '#{params[:venue]}'") if has_venue
		condition("p.position = '#{params[:position]}'") if has_position
		if params[:player_order]
			orders = params[:player_order].split(',')
			if orders.size > 2
				orders = orders.each_slice(orders.size/2).to_a
			else
				orders = [orders]
			end
			orders = orders.map{|order| order.join(" ")}.join(",")
		end
		@players = @players.where("p.name ILIKE ?", "%#{params[:search]}%") if has_search
		@players = @players.order(orders) 	if defined?(orders)
	end

	def has_venue
		['H','A'].include? params[:venue]
	end
	def has_position
		['G','D','M','F'].include? params[:position] 
	end
	def condition(cond)
		@players = @players.where(cond)
	end
	def has_search
		params[:search] != ""
	end
end

app/controllers/scrapers_controller.rb
class ScrapersController < ApplicationController
	require 'ScrapePlayerHistory'
  def launch
  	@scraper = Scraper.find(1) 
    @full_scrape = false
  end
  def start
  	logger.debug "inside start #{params.inspect}"
    if params[:full_scrape]
      full_scrape = params[:full_scrape]
    else
      full_scrape = false
    end
  	scrape_messages = ScrapePlayerHistory.new(full_scrape, Scraper.find(1)).start
    @scraper = Scraper.find(1)
    if scrape_messages
      flash.now[:notice] = "You have successfully scraped the player history"
    end      
    respond_to do |format| 
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
		def full_title(page_title)
		base_title = "FPLPlayerHistory"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/flash_helper.rb
module FlashHelper
	def flash_display
	  response = ""
	  flash.each do |name, msg|
	    response = response + 
	    	new_message(name, msg)
	  end
	  response
	end
	def new_message(name, msg)
		if name == :notice
	    content_tag(:div, msg, :id => "flash_#{name}", :class => "notice")
		else
	    content_tag(:div, msg, :id => "flash_#{name}", :class => "alert")
		end
	end					
end

app/helpers/graphs_helper.rb
module GraphsHelper
	def playerdata
		Player.order(total_points: :desc).limit(10)
	end
end

app/helpers/player_helper.rb
module PlayerHelper
	def short_name(name)
		if name.size > 9
			name.gsub!(/[aeiou]/, '')
		else
			name
		end
	end
end

app/helpers/scrapers_helper.rb
module ScrapersHelper
end

app/views/graphs/_chosen_players.html.erb
<table id=select_players>
	<thead>
		<th>Player Id</th>
		<th>Name</th>
	</thead>
	<tbody>
		<%= form_tag chosen_players_path, method: :put do %>
			<% 0.upto(9) do |i| %>
				<tr class= '<%= "splayer#{i} splayer" %>' >
					<td><%= text_field_tag "ids[]", "", readonly: true,
							class:"s_id#{i} s_id" %></td>
					<td><%= text_field_tag "names[]", "", readonly: true,
							class:"s_name#{i} s_name" %></td>
				</tr>
				<% end %>
			<tr>
				<td><%= submit_tag "Apply to Graph", class:'chosen_ones' %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/graphs/_player_table.html.erb
<table id='playertable'>
	<thead>
		<tr>
			<th>Id</th> 
			<th>Name</th> 
			<th>Club</th> 
			<th>Position</th> 
			<th>Season</th> 
			<th>Selected</th> 
			<th>Transfers Out</th> 
			<th>Transfers In</th>
			<th>Total Points</th>
			<th>Start Cost</th> 
			<th>Cost Now</th> 
		</tr>
	</thead>
	<tbody>
		<% players.each do |ply| %>
			<tr class = "<%= cycle('odd', 'even') %> person">
				<td class="player_id"><%= ply.id %></td> 
				<td class="player_name"><%= ply.name %></td>
				<td>not implemented</td>
				<td><%= ply.position %></td>
				<td><%= ply.season %></td>
				<td><%= ply.selected %></td>
				<td><%= ply.transfers_out %></td>
				<td><%= ply.transfers_in %></td>
				<td><%= ply.total_points %></td>
				<td><%= ply.cost_start %></td>
				<td><%= ply.cost_now %></th>
			</tr>
		<% end %>
	</tbody>
</table>
</br>
<div class="digg_pagination">
	<%= will_paginate players, :class => "pagination ajax", 
		remote: true%> 
</div>

app/views/graphs/top_10_bar.html.erb
<% provide(:title, "Top 10 Bar") %>
<div class="top_10_bar">
<table id='player_venue'>
	<tbody>
		<tr>
			<td><%= content_tag :div, "",id:"top10", 
				data: {players:playerdata} %></td>
		</tr>
		<tr>
			<td><div id="allplayers"> 
						<%= render "player_table", players: @players %>
					</div>
			</td>
		</tr>
	</tbody>
</table>
<div id="sidebar">
	<%= render "chosen_players" %>
</div>
</div>

app/views/graphs/top_10_bar.js.erb
$('#allplayers').empty();
$('#allplayers').html("<%= escape_javascript(render 'player_table', players: @players) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |name, msg| %>
  	<%= content_tag :div, msg, id: "flash_#{name}", class: 
  	  ("#{name}" == "notice" ? "alert alert-success" : "alert alert-danger")%>
	 <% end %>
	 <div id='ajaxmessage'></div>
	<%= yield %>

</body>
</html>

app/views/player/_player.html.erb
<% players.each do |ply| %>
	<tr class = " <%= cycle("odd", "even") %>">
		<td class="name"> <%= ply.name %></td>
		<td> <%= short_name(ply.clubname) %></td>
		<td> <%= ply.points %></td>
		<td> <%= number_with_precision(ply.range_value, precision:2) %></td>
		<td> <%= ply.cost_now %></td>
		<td> <%= ply.position %></td>
		<td> <%= ply.miniutes_played %></td>
		<td> <%= ply.points_per_game %></td>
		<td> <%= ply.points_per_min %></td>
		<td> <%= number_with_precision(ply.games, precision:0) %></td>
		<td> <%= ply.goals_scored %></td>
		<td> <%= ply.own_goals %></td>
		<td> <%= ply.penalty_saves %></td>
		<td> <%= ply.penalty_missed %></td>
		<td> <%= ply.yellow_cards %></td>
		<td> <%= ply.red_cards %></td>
		<td> <%= ply.saves %></td>
		<td> <%= ply.bonus %></td>
		<td> <%= ply.esp %></td>
		<td> <%= number_with_delimiter(ply.net_transfers) %></td>
	</tr>
<% end %>

app/views/player/comparison.html.erb
<div class="playerComparison">
	<%= form_tag filter_path, remote: true, class: 'playerFilter' do %>
		<%= hidden_field_tag :player_order, value = nil, options = {class: 'player_order'} %>
		<table class="playerControls">
			<thead>
				<tr>
	 				<th>Venue</th>
	 				<th>Position</th>
	 			</tr>
	 		</thead>
	 		<tbody>
	 			<tr>
	 				<td>		
						<div class="venue_div">
							<%= radio_button_tag(:venue, "ALL", true) %>
							<%= label_tag(:venue_all, "All venues") %>
							<%= radio_button_tag(:venue, "H") %>
							<%= label_tag(:venue_home, "Home venue") %>
							<%= radio_button_tag(:venue, "A") %>
							<%= label_tag(:venue_away, "Away venue") %>
						</end>
					</td>
					<td>
						<div class="venue_div">
							<%= radio_button_tag(:position, "ALL", true) %>
							<%= label_tag(:postion_all, "All") %>
							<%= radio_button_tag(:position, "G") %>
							<%= label_tag(:postion_goalie, "Goalie") %>
							<%= radio_button_tag(:position, "D") %>
							<%= label_tag(:postion_defender, "Defender") %>
							<%= radio_button_tag(:position, "M") %>
							<%= label_tag(:postion_midfielder, "Midfielder") %>
							<%= radio_button_tag(:position, "F") %>
							<%= label_tag(:postion_striker, "Striker") %>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<div class="range">
							<div class="from"> 
								<%= label_tag :rounds_from %>
								<%= text_field_tag :rounds_from, 1,class:"rounds_from", readonly:true, size:3 %></div>
							 <div class="to"> 
								<%= label_tag :rounds_to %>
								<%= text_field_tag :rounds_to, 38,class:"rounds_to", readonly:true, size: 3 %></div>
							</div>
						<div class='sliderContainer'>
							<div class='roundsSlider'></div>
						</div>
					</td>
					<td>
						<div class="range">
							<div class="from"> 
								<%= label_tag :price_from %>
								<%= text_field_tag :price_from, 3.0,class:"price_from", readonly:true, size:3 %></div>
							 <div class="to"> 
								<%= label_tag :price_to %>
								<%= text_field_tag :price_to, 14.0,class:"price_to", readonly:true, size: 3 %></div>
							</div>
						<div class='sliderContainer'>
							<div class='priceSlider'></div>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
		<div class="search">
			<%= label_tag(:search, "Name Search:  ")%>
			<%= text_field_tag :search %>
		</div>
		<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
		<%= submit_tag :Submit, class: "submitFilter" %>
		<button type="button" class="submitAlias">Submit</button>
	<% end %>
	<h1> Player Comparison </h1>
	<div class='fixedHeader'>
		<div class='playercontainer'>
	<table class="table playerTable">
		<thead>
			<tr class='statsHeader'>
				<th class='name'> Name </th>
				<th class='clubname'> Club </th>
				<th class='points'> Pts </th>
				<th class='range_value'>pts/prc</th>
				<th class='cost_now'>$ 2013</th>
				<th class='position'>Position</th>
				<th class='miniutes_played'> Mins</th>
				<th class='points_per_game'>PtsPGm</th>
				<th class='points_per_min'>PtsPMin</th>
				<th class='games'>Games</th>
				<th class='goals_scored'>Scored</th>
				<th class='own_goals'>Own Gls</th>
				<th class='penalty_saves'> Pen Svs </th> 
			  <th class='penalty_missed'> Pen Mss </th> 
				<th class='yellow_cards'>Yllw</th>
				<th class='red_cards'>Rd</th>
				<th class='saves'> Saves</th> 
				<th class='bonus'> Bonus</th>
				<th class='esp'> ESP</th>
				<th class='net_transfers'> Transfers</th>
			</tr>
		</thead>
		<tbody class='scrollingBody'>
		<%=	render partial: "player", locals: {players: @players} %>
		</tbody>
	</table>
		</div>
	</div>
</div>

app/views/scrapers/_scraper.html.erb
<% scraper.attributes.select{|k,v| k != 'id'}.each do |k,v| %>
	<tr class='scraperdetails'>
		<td><%= label_tag k, k.titleize %></td>
		<td><%= v %></td>
	</tr>
<% end %>

app/views/scrapers/launch.html.erb
<% provide(:title, "Launch") %>
<h2> Welcome to Player Scraper <h2>

<table id="scraper">
	<tbody id="scraper_attr"><%= render 'scraper', scraper:@scraper %>
		<%= form_tag(scraper_start_path, method: :post, remote: :true, 
				class:'scrapeform') do %>
			<tr>
				<td><%= label_tag "Full Scrape" %></td>
				<td><%= check_box_tag :full_scrape, 1, checked = true %></td>
			</tr>
			<tr></tr>
			<tr>
				<td></td>
				<td><%= submit_tag "Activate Scraper", class: "form_submit" %>
					  <%=image_tag("soccerball.gif", size:"44", class:"soccerball") %></td>
			</tr>
		<% end %>
	</tbody>
</table>